#!/usr/bin/env bash
# Build .env.production from GitHub Actions secrets/vars (no local Mac file).
# Required secrets: MYSQL_ROOT_PASSWORD, MYSQL_PASSWORD, JWT_SECRET_KEY, CERTBOT_EMAIL
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${ROOT}/.env.production"

need() {
  local name="$1" val="${!1:-}"
  if [[ -z "$val" ]]; then
    echo "Missing GitHub secret/variable: ${name}" >&2
    exit 1
  fi
}

need MYSQL_ROOT_PASSWORD
need MYSQL_PASSWORD
need JWT_SECRET_KEY
need CERTBOT_EMAIL

MYSQL_DATABASE="${MYSQL_DATABASE:-sweetcrust}"
MYSQL_USER="${MYSQL_USER:-sweetcrust}"
APP_NAME="${APP_NAME:-SweetCrust Bakery}"
AUTH_PUBLIC_BASE_URL="${AUTH_PUBLIC_BASE_URL:-https://api.skbakery.in}"
CORS_ORIGINS="${CORS_ORIGINS:-https://skbakery.in,https://www.skbakery.in,https://admin.skbakery.in,https://store.skbakery.in,https://admin.bakerywala.cloud,https://store.bakerywala.cloud,https://bakerywala.cloud,https://www.bakerywala.cloud}"
API_DOMAIN="${API_DOMAIN:-api.skbakery.in}"
EXTRA_API_DOMAINS="${EXTRA_API_DOMAINS:-api.bakerywala.cloud}"
BAKERY_NAME="${BAKERY_NAME:-SweetCrust Bakery}"
BAKERY_PHONE="${BAKERY_PHONE:-+919876543210}"
LLM_PROVIDER="${LLM_PROVIDER:-groq}"
LLM_MODEL="${LLM_MODEL:-llama-3.3-70b-versatile}"
DELIVERY_RADIUS_KM="${DELIVERY_RADIUS_KM:-100}"
MSG91_SENDER_ID="${MSG91_SENDER_ID:-SWEETCRUST}"

if [[ -z "${DATABASE_URL:-}" ]]; then
  # URL-encode password so special chars don't break the DSN
  ENC_PASS="$(python3 -c 'import urllib.parse,os; print(urllib.parse.quote(os.environ["MYSQL_PASSWORD"], safe=""))')"
  DATABASE_URL="mysql+pymysql://${MYSQL_USER}:${ENC_PASS}@mysql:3306/${MYSQL_DATABASE}"
fi

umask 077
cat >"$OUT" <<EOF
APP_NAME=${APP_NAME}
ENV=production
HOST=0.0.0.0
PORT=8000
RELOAD=false
LOG_LEVEL=INFO
LOG_JSON=true

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
DATABASE_URL=${DATABASE_URL}

REDIS_URL=redis://redis:6379/0

JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60
REFRESH_TOKEN_EXPIRE_DAYS=30
OTP_EXPIRE_MINUTES=10
OTP_DEV_CODE=

AUTH_PUBLIC_BASE_URL=${AUTH_PUBLIC_BASE_URL}
AUTH_MAIL_NOTIFY_ON_LOGIN=false
CORS_ORIGINS=${CORS_ORIGINS}
UPLOAD_DIR=uploads

BAKERY_NAME=${BAKERY_NAME}
BAKERY_PHONE=${BAKERY_PHONE}
BAKERY_GSTIN=${BAKERY_GSTIN:-}
BAKERY_UPI_ID=${BAKERY_UPI_ID:-}

SMTP_HOST=${SMTP_HOST:-}
SMTP_PORT=${SMTP_PORT:-465}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}
MAIL_FROM_NAME=${MAIL_FROM_NAME:-SweetCrust Bakery}
MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL:-}

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}

LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
GROQ_API_KEY=${GROQ_API_KEY:-}
PINECONE_API_KEY=${PINECONE_API_KEY:-}

IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY:-}
IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY:-}
IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT:-}

RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID:-}
RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET:-}
RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET:-}

DELIVERY_RADIUS_KM=${DELIVERY_RADIUS_KM}
MSG91_AUTH_KEY=${MSG91_AUTH_KEY:-}
MSG91_TEMPLATE_ID=${MSG91_TEMPLATE_ID:-}
MSG91_SENDER_ID=${MSG91_SENDER_ID}

API_DOMAIN=${API_DOMAIN}
EXTRA_API_DOMAINS=${EXTRA_API_DOMAINS}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
DEPLOY_HOST=${DEPLOY_HOST:-145.223.21.127}
DEPLOY_USER=${DEPLOY_USER:-root}
DEPLOY_PATH=${DEPLOY_PATH:-/opt/sweetcrust/backend_v2}
EOF

chmod 600 "$OUT"
echo "Rendered ${OUT}"
